### ISSUE TITLE
Ring vs. Num

### ISSUE THREAD

**Issue by Bodigrim** [chessai/semirings#40]
*I do not have a strong opinion on the matter, just speculations.*

It occurred to me that whenever one can define `Ring` instance, he can define `Num` instance as well. Namely, even if there is no sensible definition for `abs`, just make it trivial: `abs = id`, `signum = const one`, so that `abs n * signum n == n`. And `fromInteger` can be expressed in terms of `fromNatural` and `negate`. 

It is true that `Ring` is better grounded in theory, but practically it is a burden in comparison to `Num`. And I am inclined to say that `Ring` does not have enough advantages to overweight this mental overhead. 

@chessai @andrewthad what is your opinion?

**Comment by chessai** [comment]
One of the motivations of this package (certainly not the only one) is to avoid Num, whose existence is a pet peeve of mine. The reason I wrote `Ring` was to not have to depend on `Num` at all in my own projects, aside from `fromInteger` (convenient if i'm writing Semiring-polymorphic code, because then I don't need a Semiring and Num constraint). This is because, as you say, 

> It occurred to me that whenever one can define Ring instance, he can define Num instance as well.

To me, this has always been a pro for `Ring`, because to me it means that Num is bloated. However, from another perspective, it could be seen as a con, since `Num` is clearly dominant in terms of API wide-spreadedness, and following from this, `Ring` becomes an overhead for anything that has to integrate with code that uses Num.

However, I can see that others may not share in this distaste so much, so I can understand how it might actually be burdensome. From your perspective, as a maintainer of arithmoi, i can see how you might find it annoying (annoying mostly means "translates to mental overhead") since your usage of the package does not involve the supplanting of num by semiring. In several of my projects i write a custom prelude that exports Semiring/Ring.

I try to not let this pet peeve become impractical, but you can see it manifest itself when I am presented with the idea of adding `Field`, which I started to reconsider after you pointed out that `Fractional` is not so bad and provides essentially the same API. Still not sure if we should add Field after you pointed this out, since `semirings` doesn't really have 'alternative numeric hierarchy' as a goal.

As far as Ring, I'm unsure. This comment up to now mostly serves as a way to explain my background on the issue.

It's certainly true that the `Ring` api is less "useful" in terms of percentage of use-sites when compared to "Semiring".

Here are some pros/cons off the top of my head:

Pros:
  * Don't need to include Num constraints in polymorphic code (if you're just using (-) or negate)
  * We can include `ringLaws` in quickcheck-classes, a subset of `numLaws` (which is not in quickcheck-classes but should be)
  * Semiring/Ring are accurate for types where abs/signum are not well-defined/not useful
Cons:
  * Having to integrate with code that uses Num induces more mental overhead and essentially redundant constraints/APIs

I'm sure there are more pros/cons, but i cannot think of any after a quick reflection.

Overall I can't say I'm in favour of removal, but I'd want to hear more cons.

**Comment by Bodigrim** [comment]
I have a similar kind of a pet peeve, but about `Integral` :)

*Mental overhead* is mostly about users having to learn one more concept and making an educated choice between them. 

IMO the main cons is a usual issue with type classes, when one needs to combine a class from one library and a type from another. E. g., to plug into a `Ring`-based API something with `Num` instance only (e. g., gaussian integers from `arithmoi` or quaternions from `cayley-dickson`). If you are lucky, you can get along with coercing to `WrappedNum` and back (aka *compile-time overhead*), but things become worse if it involves casting `Set` or `Map` (aka *runtime overhead*).

Practically it means that whenever I design a *public* library (even built atop of `semirings`), I should prefer `Num` over `Ring`.

But surely, if you extensively use `Ring` in *private* projects, it may well offset the cost of maintenance of an additional type class.

**Comment by Bodigrim** [comment]
Pros: we have 

```haskell
instance Ring a => Ring (Complex a)
```

but `Num` instance requires significantly stronger constraint (because of `abs` / `signum`)

```haskell
instance RealFloat a => Num (Complex a)
```

--- 

BTW @chessai is there a reason behind `quickcheck-classes` lack of `numLaws`?

**Comment by chessai** [comment]
Havent had time to respond to the previous comment, but quickcheck-classes should have numLaws, i just forgot to write it.

**Comment by Bodigrim** [comment]
Closing, because we have gone full ahead with `Ring` and `Field` classes.
