### ISSUE TITLE
New poly type for faster multiplication

### ISSUE THREAD

**Issue by aljce** [chessai/semirings#8]
So there is a [faster polynomial multiplication algorithm](http://algorithm.cs.nthu.edu.tw/~course/Extra_Info/Divide%20and%20Conquer_supplement.pdf) that requires a ring constraint instead of a semiring. This additional constraint brings the running time down from O(n^2) to O(n^lg3).
You should have type:
```haskell
newtype RingPoly a = ...
```
That types semiring instance should require a to be a ring.

**Comment by chessai** [comment]
not going to focus on this right now, but it will be done

**Comment by chessai** [comment]
I want to include both options, in case someone provides an underlying type that is not a Ring, but at least a Semiring. I see two choices give this desire:

1. Make the semiring instance for 'Poly a' require a Ring instance for 'a', implement the asymptotically faster algorithm as the default, and provide another function for multiplying two polynomials in a semiring.
2. Keep the semiring instance as-is and provide a function for multiplying two polynomials using the asymptotically faster algorithm.

I am in favour of (2), because it is the least restrictive in its constraint, which I view as generally better. This is offset only by the inconvenience of not having `(*)` or `times` not performing asymptotically best, but I believe this is not a sufficient reason to choose (1) so long as the faster algorithm is provided. An argument I see against this reasoning is that statistically, most types are Rings, and not just Semirings. But I'm still not sure in that case. I would like feedback.

**Comment by aljce** [comment]
You dont have a third option which is the one i suggested and I stand by that one being the best

**Comment by chessai** [comment]
What

**Comment by chessai** [comment]
create a second type, RingPoly, and an iso between RingPoly and Poly

**Comment by chessai** [comment]
moved to https://github.com/chessai/semirings-types/issues/1
